pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Source code is already checked out by Jenkins.'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

    }

    post {
        success {
            echo 'Build completed successfully!'
        }

        failure {
            echo 'Build failed.'
        }
    }
}
